/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrimeiroAcessoRouteImport } from './routes/primeiro-acesso'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSistemasRouteImport } from './routes/_authenticated/sistemas'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPendenciasRouteImport } from './routes/_authenticated/pendencias'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedMinhaMatrizRouteImport } from './routes/_authenticated/minha-matriz'
import { Route as AuthenticatedMatrizAcessosRouteImport } from './routes/_authenticated/matriz-acessos'
import { Route as AuthenticatedLixeiraRouteImport } from './routes/_authenticated/lixeira'
import { Route as AuthenticatedListaAcessosRouteImport } from './routes/_authenticated/lista-acessos'
import { Route as AuthenticatedInativosRouteImport } from './routes/_authenticated/inativos'
import { Route as AuthenticatedImportarRouteImport } from './routes/_authenticated/importar'
import { Route as AuthenticatedIaRouteImport } from './routes/_authenticated/ia'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCredenciaisRouteImport } from './routes/_authenticated/credenciais'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedChamadosRouteImport } from './routes/_authenticated/chamados'
import { Route as AuthenticatedAdministracaoRouteImport } from './routes/_authenticated/administracao'
import { Route as AuthenticatedAcessosRouteImport } from './routes/_authenticated/acessos'
import { Route as AuthenticatedColaboradoresIndexRouteImport } from './routes/_authenticated/colaboradores.index'
import { Route as AuthenticatedColaboradoresIdRouteImport } from './routes/_authenticated/colaboradores.$id'

const PrimeiroAcessoRoute = PrimeiroAcessoRouteImport.update({
  id: '/primeiro-acesso',
  path: '/primeiro-acesso',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSistemasRoute = AuthenticatedSistemasRouteImport.update({
  id: '/sistemas',
  path: '/sistemas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPendenciasRoute = AuthenticatedPendenciasRouteImport.update({
  id: '/pendencias',
  path: '/pendencias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMinhaMatrizRoute =
  AuthenticatedMinhaMatrizRouteImport.update({
    id: '/minha-matriz',
    path: '/minha-matriz',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMatrizAcessosRoute =
  AuthenticatedMatrizAcessosRouteImport.update({
    id: '/matriz-acessos',
    path: '/matriz-acessos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLixeiraRoute = AuthenticatedLixeiraRouteImport.update({
  id: '/lixeira',
  path: '/lixeira',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListaAcessosRoute =
  AuthenticatedListaAcessosRouteImport.update({
    id: '/lista-acessos',
    path: '/lista-acessos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInativosRoute = AuthenticatedInativosRouteImport.update({
  id: '/inativos',
  path: '/inativos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportarRoute = AuthenticatedImportarRouteImport.update({
  id: '/importar',
  path: '/importar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIaRoute = AuthenticatedIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCredenciaisRoute =
  AuthenticatedCredenciaisRouteImport.update({
    id: '/credenciais',
    path: '/credenciais',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChamadosRoute = AuthenticatedChamadosRouteImport.update({
  id: '/chamados',
  path: '/chamados',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdministracaoRoute =
  AuthenticatedAdministracaoRouteImport.update({
    id: '/administracao',
    path: '/administracao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcessosRoute = AuthenticatedAcessosRouteImport.update({
  id: '/acessos',
  path: '/acessos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedColaboradoresIndexRoute =
  AuthenticatedColaboradoresIndexRouteImport.update({
    id: '/colaboradores/',
    path: '/colaboradores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedColaboradoresIdRoute =
  AuthenticatedColaboradoresIdRouteImport.update({
    id: '/colaboradores/$id',
    path: '/colaboradores/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/acessos': typeof AuthenticatedAcessosRoute
  '/administracao': typeof AuthenticatedAdministracaoRoute
  '/chamados': typeof AuthenticatedChamadosRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/credenciais': typeof AuthenticatedCredenciaisRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/ia': typeof AuthenticatedIaRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/inativos': typeof AuthenticatedInativosRoute
  '/lista-acessos': typeof AuthenticatedListaAcessosRoute
  '/lixeira': typeof AuthenticatedLixeiraRoute
  '/matriz-acessos': typeof AuthenticatedMatrizAcessosRoute
  '/minha-matriz': typeof AuthenticatedMinhaMatrizRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/pendencias': typeof AuthenticatedPendenciasRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/sistemas': typeof AuthenticatedSistemasRoute
  '/colaboradores/$id': typeof AuthenticatedColaboradoresIdRoute
  '/colaboradores/': typeof AuthenticatedColaboradoresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/acessos': typeof AuthenticatedAcessosRoute
  '/administracao': typeof AuthenticatedAdministracaoRoute
  '/chamados': typeof AuthenticatedChamadosRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/credenciais': typeof AuthenticatedCredenciaisRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/ia': typeof AuthenticatedIaRoute
  '/importar': typeof AuthenticatedImportarRoute
  '/inativos': typeof AuthenticatedInativosRoute
  '/lista-acessos': typeof AuthenticatedListaAcessosRoute
  '/lixeira': typeof AuthenticatedLixeiraRoute
  '/matriz-acessos': typeof AuthenticatedMatrizAcessosRoute
  '/minha-matriz': typeof AuthenticatedMinhaMatrizRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/pendencias': typeof AuthenticatedPendenciasRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/sistemas': typeof AuthenticatedSistemasRoute
  '/colaboradores/$id': typeof AuthenticatedColaboradoresIdRoute
  '/colaboradores': typeof AuthenticatedColaboradoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/primeiro-acesso': typeof PrimeiroAcessoRoute
  '/_authenticated/acessos': typeof AuthenticatedAcessosRoute
  '/_authenticated/administracao': typeof AuthenticatedAdministracaoRoute
  '/_authenticated/chamados': typeof AuthenticatedChamadosRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/credenciais': typeof AuthenticatedCredenciaisRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/ia': typeof AuthenticatedIaRoute
  '/_authenticated/importar': typeof AuthenticatedImportarRoute
  '/_authenticated/inativos': typeof AuthenticatedInativosRoute
  '/_authenticated/lista-acessos': typeof AuthenticatedListaAcessosRoute
  '/_authenticated/lixeira': typeof AuthenticatedLixeiraRoute
  '/_authenticated/matriz-acessos': typeof AuthenticatedMatrizAcessosRoute
  '/_authenticated/minha-matriz': typeof AuthenticatedMinhaMatrizRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/pendencias': typeof AuthenticatedPendenciasRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/sistemas': typeof AuthenticatedSistemasRoute
  '/_authenticated/colaboradores/$id': typeof AuthenticatedColaboradoresIdRoute
  '/_authenticated/colaboradores/': typeof AuthenticatedColaboradoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/primeiro-acesso'
    | '/acessos'
    | '/administracao'
    | '/chamados'
    | '/configuracoes'
    | '/credenciais'
    | '/dashboard'
    | '/historico'
    | '/ia'
    | '/importar'
    | '/inativos'
    | '/lista-acessos'
    | '/lixeira'
    | '/matriz-acessos'
    | '/minha-matriz'
    | '/notificacoes'
    | '/pendencias'
    | '/perfil'
    | '/relatorios'
    | '/sistemas'
    | '/colaboradores/$id'
    | '/colaboradores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/primeiro-acesso'
    | '/acessos'
    | '/administracao'
    | '/chamados'
    | '/configuracoes'
    | '/credenciais'
    | '/dashboard'
    | '/historico'
    | '/ia'
    | '/importar'
    | '/inativos'
    | '/lista-acessos'
    | '/lixeira'
    | '/matriz-acessos'
    | '/minha-matriz'
    | '/notificacoes'
    | '/pendencias'
    | '/perfil'
    | '/relatorios'
    | '/sistemas'
    | '/colaboradores/$id'
    | '/colaboradores'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/primeiro-acesso'
    | '/_authenticated/acessos'
    | '/_authenticated/administracao'
    | '/_authenticated/chamados'
    | '/_authenticated/configuracoes'
    | '/_authenticated/credenciais'
    | '/_authenticated/dashboard'
    | '/_authenticated/historico'
    | '/_authenticated/ia'
    | '/_authenticated/importar'
    | '/_authenticated/inativos'
    | '/_authenticated/lista-acessos'
    | '/_authenticated/lixeira'
    | '/_authenticated/matriz-acessos'
    | '/_authenticated/minha-matriz'
    | '/_authenticated/notificacoes'
    | '/_authenticated/pendencias'
    | '/_authenticated/perfil'
    | '/_authenticated/relatorios'
    | '/_authenticated/sistemas'
    | '/_authenticated/colaboradores/$id'
    | '/_authenticated/colaboradores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PrimeiroAcessoRoute: typeof PrimeiroAcessoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/primeiro-acesso': {
      id: '/primeiro-acesso'
      path: '/primeiro-acesso'
      fullPath: '/primeiro-acesso'
      preLoaderRoute: typeof PrimeiroAcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sistemas': {
      id: '/_authenticated/sistemas'
      path: '/sistemas'
      fullPath: '/sistemas'
      preLoaderRoute: typeof AuthenticatedSistemasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pendencias': {
      id: '/_authenticated/pendencias'
      path: '/pendencias'
      fullPath: '/pendencias'
      preLoaderRoute: typeof AuthenticatedPendenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minha-matriz': {
      id: '/_authenticated/minha-matriz'
      path: '/minha-matriz'
      fullPath: '/minha-matriz'
      preLoaderRoute: typeof AuthenticatedMinhaMatrizRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/matriz-acessos': {
      id: '/_authenticated/matriz-acessos'
      path: '/matriz-acessos'
      fullPath: '/matriz-acessos'
      preLoaderRoute: typeof AuthenticatedMatrizAcessosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lixeira': {
      id: '/_authenticated/lixeira'
      path: '/lixeira'
      fullPath: '/lixeira'
      preLoaderRoute: typeof AuthenticatedLixeiraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lista-acessos': {
      id: '/_authenticated/lista-acessos'
      path: '/lista-acessos'
      fullPath: '/lista-acessos'
      preLoaderRoute: typeof AuthenticatedListaAcessosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inativos': {
      id: '/_authenticated/inativos'
      path: '/inativos'
      fullPath: '/inativos'
      preLoaderRoute: typeof AuthenticatedInativosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/importar': {
      id: '/_authenticated/importar'
      path: '/importar'
      fullPath: '/importar'
      preLoaderRoute: typeof AuthenticatedImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ia': {
      id: '/_authenticated/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof AuthenticatedIaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/credenciais': {
      id: '/_authenticated/credenciais'
      path: '/credenciais'
      fullPath: '/credenciais'
      preLoaderRoute: typeof AuthenticatedCredenciaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chamados': {
      id: '/_authenticated/chamados'
      path: '/chamados'
      fullPath: '/chamados'
      preLoaderRoute: typeof AuthenticatedChamadosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/administracao': {
      id: '/_authenticated/administracao'
      path: '/administracao'
      fullPath: '/administracao'
      preLoaderRoute: typeof AuthenticatedAdministracaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/acessos': {
      id: '/_authenticated/acessos'
      path: '/acessos'
      fullPath: '/acessos'
      preLoaderRoute: typeof AuthenticatedAcessosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/colaboradores/': {
      id: '/_authenticated/colaboradores/'
      path: '/colaboradores'
      fullPath: '/colaboradores/'
      preLoaderRoute: typeof AuthenticatedColaboradoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/colaboradores/$id': {
      id: '/_authenticated/colaboradores/$id'
      path: '/colaboradores/$id'
      fullPath: '/colaboradores/$id'
      preLoaderRoute: typeof AuthenticatedColaboradoresIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAcessosRoute: typeof AuthenticatedAcessosRoute
  AuthenticatedAdministracaoRoute: typeof AuthenticatedAdministracaoRoute
  AuthenticatedChamadosRoute: typeof AuthenticatedChamadosRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedCredenciaisRoute: typeof AuthenticatedCredenciaisRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedIaRoute: typeof AuthenticatedIaRoute
  AuthenticatedImportarRoute: typeof AuthenticatedImportarRoute
  AuthenticatedInativosRoute: typeof AuthenticatedInativosRoute
  AuthenticatedListaAcessosRoute: typeof AuthenticatedListaAcessosRoute
  AuthenticatedLixeiraRoute: typeof AuthenticatedLixeiraRoute
  AuthenticatedMatrizAcessosRoute: typeof AuthenticatedMatrizAcessosRoute
  AuthenticatedMinhaMatrizRoute: typeof AuthenticatedMinhaMatrizRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedPendenciasRoute: typeof AuthenticatedPendenciasRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedSistemasRoute: typeof AuthenticatedSistemasRoute
  AuthenticatedColaboradoresIdRoute: typeof AuthenticatedColaboradoresIdRoute
  AuthenticatedColaboradoresIndexRoute: typeof AuthenticatedColaboradoresIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAcessosRoute: AuthenticatedAcessosRoute,
  AuthenticatedAdministracaoRoute: AuthenticatedAdministracaoRoute,
  AuthenticatedChamadosRoute: AuthenticatedChamadosRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedCredenciaisRoute: AuthenticatedCredenciaisRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedIaRoute: AuthenticatedIaRoute,
  AuthenticatedImportarRoute: AuthenticatedImportarRoute,
  AuthenticatedInativosRoute: AuthenticatedInativosRoute,
  AuthenticatedListaAcessosRoute: AuthenticatedListaAcessosRoute,
  AuthenticatedLixeiraRoute: AuthenticatedLixeiraRoute,
  AuthenticatedMatrizAcessosRoute: AuthenticatedMatrizAcessosRoute,
  AuthenticatedMinhaMatrizRoute: AuthenticatedMinhaMatrizRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedPendenciasRoute: AuthenticatedPendenciasRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedSistemasRoute: AuthenticatedSistemasRoute,
  AuthenticatedColaboradoresIdRoute: AuthenticatedColaboradoresIdRoute,
  AuthenticatedColaboradoresIndexRoute: AuthenticatedColaboradoresIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PrimeiroAcessoRoute: PrimeiroAcessoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
